### ISSUE TITLE
Feature Request: Edit text as in Scratch 2.0

### ISSUE THREAD

**Issue by jwzimmer-zz** [fsih/papergrapher#72] opened 2017-07-06 20:27 UTC
Reported by Shruti during Paint Editor Internal Playtest 7/6/17:
> would be nice to edit the text like in scratch 2.0 and not in a separate box.

Chrome, Mac OS, Blobs+

**Label:** blobs+

**Comment by fsih** [comment] 2017-07-06 21:16
Dupe of https://github.com/fsih/papergrapher/issues/23

**Closed as completed by fsih** 2017-07-06 21:16 UTC
