### ISSUE TITLE
Feature request: forward/ backward a layer

### ISSUE THREAD

**Issue by jwzimmer-zz** [fsih/papergrapher#71] opened 2017-07-06 20:01 UTC
Reported by @seotts during Paint Editor Internal Playtest 7/6/17:
> I think i need forward/backward layer in addition to all the way forward / all the way back. Particularly when adding objects to existing sprites (i.e. adding a guitar to the bear)

**Comment by fsih** [comment] 2017-07-06 21:15
Dupe of https://github.com/fsih/papergrapher/issues/9

**Closed as completed by fsih** 2017-07-06 21:15 UTC
